version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: peliculas
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    command: --init-file /data/application/init.sql
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/data/application/init.sql

  app:
    build: .
    depends_on:
      - mysql
    ports:
      - "8080:8080"
